language: cpp

cache:
    directories:
      - $HOME/cmake

sudo: false

compiler:
    - clang
    - gcc

notifications:
    email: false
    irc: "chat.freenode.net#stepmania-devs"

addons:
    apt:
        packages:
            - nasm
            - libmad0-dev
            - libgtk2.0-dev
            - binutils-dev
            - libasound-dev
            - libpulse-dev
            - libjack-dev
            - libc6-dev
            - libogg-dev
            - libvorbis-dev
            - libbz2-dev
            - libjpeg9-dev
            - libpng12-dev
            - libxtst-dev
            - libxrandr-dev
            - libglu1-mesa-dev
            - mesa-common-dev
            - libglew-dev

before_script:
    - bash .install-cmake.sh

script:
    - cd Build
    - $HOME/cmake/bin/cmake -DWITH_PORTABLE_TOMCRYPT=ON -G 'Unix Makefiles' ..
    - make
